version: "3.9"

services:
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: instabug_challenge_dev
    volumes:
      - db_data:/var/lib/mysql/
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - default

  redis:
    image: redis
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    build: .
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql:mysql

  sidekiq:
    build: .
    volumes:
      - '.:/app'
    depends_on:
      - redis
      - app

  elasticsearch:
    image: elasticsearch:8.4.0
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false

  rabbitmq:
    image: rabbitmq:3.9.22-management
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:15672"

  sneakers:
    build: .
    command: bundle exec rake sneakers:run
    depends_on:
      - app
      - rabbitmq
    volumes:
      - .:/app
    environment:
      - WORKERS=ChatsRabbitConsumer,MessagesRabbitConsumer

volumes:
  db_data:
  redis:
  elastic:
  rabbitmq:
