version: "3.9"
services:
  mysql:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: pswd
      MYSQL_DATABASE: instabug_challenge_dev
    volumes:
      - db_data:/var/lib/mysql/
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - default

  redis:
    image: redis
    command: bash -c "redis-server"
    environment:
      REDIS_URL: redis://0.0.0.0:6379/0
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/app'
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    links:
      - mysql:mysql

  sidekiq:
    build: .
    command: bash -c "bundle exec sidekiq restart"
    volumes:
      - '.:/app'
    depends_on:
      - redis
      - app
    networks:
      - default

  elasticsearch:
    image: elasticsearch:8.4.0
    ports:
      - "9200:9200"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false


volumes:
  db_data:
  redis:
  elastic:
