---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/applications":
    get:
      summary: Retrieves all the created applications
      tags:
      - Application
      responses:
        '200':
          description: Applications retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    created_at:
                      type: string
                    updated_at:
                      type: string
                  required:
                  - name
                  - created_at
                  - updated_at
        '422':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
    post:
      summary: Creates a new Application
      tags:
      - Application
      parameters: []
      responses:
        '201':
          description: Application created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  application:
                    type: object
                    properties:
                      name:
                        type: string
                      token:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - name
                    - token
                    - created_at
                    - updated_at
                required:
                - message
                - application
        '422':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/applications/{token}":
    get:
      summary: Retrieves the given token's applications
      tags:
      - Application
      parameters:
      - name: token
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Applications retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  token:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - name
                - token
                - created_at
                - updated_at
        '422':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
    put:
      summary: Update Application
      tags:
      - Application
      parameters: []
      responses:
        '200':
          description: Application updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  application:
                    type: object
                    properties:
                      name:
                        type: string
                      token:
                        type: string
                      created_at:
                        type: string
                      updated_at:
                        type: string
                    required:
                    - name
                    - token
                    - created_at
                    - updated_at
                required:
                - message
                - application
        '422':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                required:
                - message
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
